version: '3.7'

services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.13.1-alpine #https://hub.docker.com/r/portainer/portainer-ce/tags
    restart: always
    ports: [9000]
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - npm
networks:
  npm:
    external: true
    name: npm
