version: '3.3'

services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.11.1
    restart: always
    ports:
      - 9999:9000
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
